<?php
/**
 * Created by PhpStorm.
 * User: Kaephas
 * Date: 5/18/2019
 * Time: 10:02
 */

//Turn on error reporting
ini_set('display_errors' ,1);
ini_set('file_uploads', 1);
error_reporting(E_ALL);

//require autoload file
require_once 'vendor/autoload.php';
require_once 'model/validate.php';
require_once 'model/option_functions.php';

session_start();

//create an instance of the Base class
$f3 = Base::instance();

$f3->set('DEBUG', 3);

$f3->set('glasses', generateGlasses());
$f3->set('typeList', generateIngTypes());
$f3->set('alcohols', array('cognac', 'gin', 'pisco', 'rum', 'tequila', 'vermouth', 'vodka', 'whiskey', 'liquor'));


$db = new Database();

//Define a default route (dating splash page)
$f3->route('GET /', function($f3)
{
    $pageTitle = "D&D&D";
    $f3->set('pageTitle', $pageTitle);

    $view = new Template();
    echo $view->render('views/home.html');
});

$f3->route('GET|POST /find_drink', function($f3)
{
    $pageTitle = "Find My Drink";
    $f3->set('pageTitle', $pageTitle);

    $f3->set('classes', generateClasses());
    // html generated by js, but validation from f3
    $f3->set('subclasses', generateSubClasses());
    $f3->set('stats', generateStats());
    $f3->set('alignments', generateAlignments());
    $f3->set('backgrounds', generateBackgrounds());

    $view = new Template();
    echo $view->render('views/character.html');
});

$f3->route('GET|POST /add_drink', function($f3)
{
    $pageTitle = "Add a Drink";
    $f3->set('pageTitle', $pageTitle);

    $view = new Template();
    echo $view->render('views/add_drink.html');
});

$f3->route('GET /drinks', function($f3) {
    global $db;
    $drinks = $db->getAllDrinks();

    $pageTitle = "Drink List";
    $f3->set('pageTitle', $pageTitle);

    $f3->set('drinks', $drinks);

    $view = new Template();
    echo $view->render('views/view_drinks.html');
});

// edit drinks
$f3->route('GET|POST /drinks/@drink', function($f3, $params) {
    $drink = $params['drink'];
    global $db;
    $info = $db->editDrink($drink);
    $f3->set('oldName', $info->getName());
    $f3->set('drink', $info);

    $f3->set('name', $info->getName());
    $f3->set('drinkGlass', $info->getGlass());
    $f3->set('qtys', $info->getQty());
    $f3->set('ings', $info->getIngredients());
    $f3->set('types', $info->getType());
    $f3->set('recipe', $info->getRecipe());
    $f3->set('drinkImg', $info->getImage());

    if(get_class($info) == 'AlcoholDrink') {

        $f3->set('shots', $info->getShots());
    } else {
        $f3->set('shots', 0);
    }

    if(!empty($_POST)) {
        // validate
        $name = $_POST['name'];
        $glass = $_POST['glass'];
        $shots = $_POST['shots'];
        $qtys = $_POST['qtys'];
        $ings = $_POST['ings'];
        $types = $_POST['types'];
        $recipe = $_POST['recipe'];

        $f3->set('name', $name);
        $f3->set('drinkGlass', $glass);
        $f3->set('shots', $shots);
        $f3->set('qtys', $qtys);
        $f3->set('ings', $ings);
        $f3->set('types', $types);
        $f3->set('recipe', $recipe);

        $validate = validInfo();

        $validateImg = true;
        if(!empty($_FILES['drinkImg']['name'])) {
            $image = $_FILES['drinkImg'];
            $f3->set('drinkImg', $_FILES['drinkImg']);

            // get storage path to attempt
            $path = 'images/' . basename($image["name"]);

            $validateImg = validImage($image, $path);
            // if uploaded update Drink object
            if($validateImg) {
                $f3->get('drink')->setImage($path);
            }
        }
        $f3->set('drinkImg', $f3->get('drink')->getImage());

        $validate = $validate && $validateImg;

        if($validate) {
            $_SESSION['old'] = $f3->get('oldName');
            $_SESSION['new'] = $f3->get('drink')->getName();
            $_SESSION['drink'] = $f3->get('drink');
            // drink has been updated during validation
            echo '<br>Drink info: ';
            var_dump($f3->get('drink'));
            // update database
            $db->updateDrink($f3->get('drink'), $f3->get('oldName'));
            // reroute to all drinks? Back to self with notice of success?
            $f3->reroute('/test');
        }

    }

    //$f3->set('ingTypes', $info->getType());
    $view = new Template();
    echo $view->render('views/edit_drink.html');
});

$f3->route('GET /test', function($f3) {
    $f3->set('old', $_SESSION['old']);
    $f3->set('new', $_SESSION['new']);
    $f3->set('drink', $_SESSION['drink']);

    $view = new Template();
    echo $view->render('views/test.html');
});

$f3->run();